version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: foodie_db
      POSTGRES_USER: foodie
      POSTGRES_PASSWORD: secret
    ports:
      - '5342:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: foodie
      DB_PASSWORD: secret
      DB_NAME: foodie_db
      JWT_SECRET: your_jwt_secret
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - app_node_modules:/app/node_modules
    command: yarn dev
volumes:
  db_data:
  app_node_modules:
